---
title: "Reshaping data with tidyr - Messy (2)"
author: "Heike Hofmann"
date: "`r Sys.Date()`"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---
class: middle, inverse, center
# Messy (2)


---

# separate

Messy (2): Multiple variables are stored in one column

```{r, message=FALSE, warning = FALSE}
library(tidyverse)
df <- data.frame(x = c(NA, "a.b", "a.d", "b.c"))
df
df %>% separate(x, into = c("A", "B"))
```

---
class: inverse
# Your Turn (5 min)


The Iowa Data Portal is a wealth of information on and about the State of Iowa. 

The website 
[Liquor Sales](https://data.iowa.gov/Sales-Distribution/Iowa-Liquor-Sales/m3tr-qhgy) provides data on every liquor sale in a licensed store in Iowa. The code below reads (part of) the data into an R session.

```
url <- "https://github.com/Stat579-at-ISU/materials/blob/master/03_tidyverse/data/Iowa_Liquor_Sales.csv.zip?raw=TRUE"
download.file(url, "iowa.zip")
iowa <- readr::read_csv("iowa.zip")
```

Assess the 'messiness' of the data. List issues that prevent us from working with the data directly. Which of these issues are of type (1) or (2) of messiness?

---
class: inverse
# Your Turn - Fast Fingers

Run the following code to load the Iowa Liquor Sales into your working session

```
url <- "https://github.com/Stat579-at-ISU/materials/blob/master/03_tidyverse/data/Iowa_Liquor_Sales.csv.zip?raw=TRUE"
download.file(url, "iowa.zip")
iowa <- readr::read_csv("iowa.zip")
```
Open the Fast Fingers Quiz in Canvas for a chance to earn 5 points of extra credit. Good luck!

---

# Problems with the data

- `Date` is text, in the format of Month/Day/Year (Messy 2)

- Store location is a textual expression of form `POINT (`...`)` and geographic latitude and longitude. (Messy 2)


no Messy 1? - problems of type Messy 1 are typically hard to detect and often up to interpretation/dependent on the analysis to be done.

---
class: inverse
# Your Turn (10 min)


- Check the help for the function `parse_number` in the `readr` package and use it on the store location. What result do you get?

- Use `separate` to split the date variable into year, month and day.

- Use `separate` again to extract geographic latitude and longitude (Hint - you might need several steps of `separate`)

---
class: inverse
# Your Turn - exploration (10 mins)

Use `dplyr` functionality to answer the following questions:

  1. What is the total amount spent on Liquor Sales?

  2. What is the single largest sale (in volume/in dollar amount)?
<!--  3. What time frame does the campaign expenditure cover?-->

  4. Plot geographic longitude and latitude. Where are liquor sales in Ames happening? 


